/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 bookcase.gltf 
Author: 3D_for_everyone (https://sketchfab.com/boglarka4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bookcase-eac9c98de25c429a9f5df719ac2fb261
Title: Bookcase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bookcase(props) {
  const { nodes, materials } = useGLTF('/3dModels/Bookcase/bookcase.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.07, -0.019, 1.17]} rotation={[0.21, 0, 0]} scale={1.217}>
            <mesh geometry={nodes.Book_1_Book_1_0.geometry} material={materials.Book_1} />
            <mesh geometry={nodes.Book_1_Book_1_paper_0.geometry} material={materials.Book_1_paper} />
          </group>
          <group position={[0.081, -0.094, 1.484]} rotation={[Math.PI / 2, -0.199, 0]} scale={1.246}>
            <mesh geometry={nodes.Book_2_Book_2_0.geometry} material={materials.Book_2} />
            <mesh geometry={nodes.Book_2_Book_2_paper_0.geometry} material={materials.Book_2_paper} />
          </group>
          <group position={[0.11, -0.107, 0.646]} rotation={[Math.PI / 2, -0.099, 0]} scale={1.505}>
            <mesh geometry={nodes.Book_3_Book_3_0.geometry} material={materials.Book_3} />
            <mesh geometry={nodes.Book_3_Book_3_paper_0.geometry} material={materials.Book_3_paper} />
          </group>
          <group position={[0.063, -0.063, 0.709]} rotation={[Math.PI / 2, 0.246, 0]} scale={1.236}>
            <mesh geometry={nodes.Book_4_Book_4_0.geometry} material={materials.Book_4} />
            <mesh geometry={nodes.Book_4_Book_4_paper_0.geometry} material={materials.Book_4_paper} />
          </group>
          <group position={[0.039, 0.032, 1.171]} rotation={[0.216, 0, 0]} scale={1.361}>
            <mesh geometry={nodes.Book_5_Book_5_0.geometry} material={materials.Book_5} />
            <mesh geometry={nodes.Book_5_Book_5_paper_0.geometry} material={materials.Book_5_paper} />
          </group>
          <group position={[0.116, -0.004, 0.361]} rotation={[0.084, 0, 0]} scale={1.935}>
            <mesh geometry={nodes.Book_6_Book_6_0.geometry} material={materials.Book_6} />
            <mesh geometry={nodes.Book_6_Book_6_paper_0.geometry} material={materials.Book_6_paper} />
          </group>
          <group position={[0.097, -0.052, 0.383]} scale={[1.353, 1.036, 1.353]}>
            <mesh geometry={nodes.Book_7_Book_7_0.geometry} material={materials.Book_7} />
            <mesh geometry={nodes.Book_7_Book_7_paper_0.geometry} material={materials.Book_7_paper} />
          </group>
          <group position={[0.061, 0.18, 0.364]} scale={[1.439, 1.886, 1.322]}>
            <mesh geometry={nodes.Book_8_Book_8_0.geometry} material={materials.Book_8} />
            <mesh geometry={nodes.Book_8_Book_8_paper_0.geometry} material={materials.Book_8_paper} />
          </group>
          <group position={[0.078, -0.088, 1.509]} rotation={[Math.PI / 2, 0, 0]} scale={[1.343, 2.54, 1.447]}>
            <mesh geometry={nodes.Book_9_Book_9_0.geometry} material={materials.Book_9} />
            <mesh geometry={nodes.Book_9_Book_9_paper_0.geometry} material={materials.Book_9_paper} />
          </group>
          <group position={[0.057, 0.102, 1.147]} rotation={[0.279, 0, 0]} scale={1.157}>
            <mesh geometry={nodes.Book_10_Book_10_0.geometry} material={materials.Book_10} />
            <mesh geometry={nodes.Book_10_Book_10_paper_0.geometry} material={materials.Book_10_paper} />
          </group>
          <group position={[0.059, 0.252, 1.176]} scale={[1.306, 1, 1.306]}>
            <mesh geometry={nodes.Book_11_Book_11_0.geometry} material={materials.Book_11} />
            <mesh geometry={nodes.Book_11_Book_11_paper_0.geometry} material={materials.Book_11_paper} />
          </group>
          <group position={[0.054, 0.114, 0.357]} rotation={[-0.178, 0, 0]} scale={1.314}>
            <mesh geometry={nodes.Book_12_Book_12_0.geometry} material={materials.Book_12} />
            <mesh geometry={nodes.Book_12_Book_12_paper_0.geometry} material={materials.Book_12_paper} />
          </group>
          <group position={[0.057, 0.208, 1.134]} rotation={[-0.089, 0, 0]} scale={1.558}>
            <mesh geometry={nodes.Book_13_Book_13_0.geometry} material={materials.Book_13} />
            <mesh geometry={nodes.Book_13_Book_13_paper_0.geometry} material={materials.Book_13_paper} />
          </group>
          <group position={[0.079, -0.095, 1.447]} rotation={[Math.PI / 2, 0, 0]} scale={1.246}>
            <mesh geometry={nodes.Book_14_Book_14_0.geometry} material={materials.Book_14} />
            <mesh geometry={nodes.Book_14_Book_14_paper_0.geometry} material={materials.Book_14_paper} />
          </group>
          <group position={[0.024, 0.063, 1.163]} rotation={[0.225, 0, 0]} scale={1.286}>
            <mesh geometry={nodes.Book_15_Book_15_0.geometry} material={materials.Book_15} />
            <mesh geometry={nodes.Book_15_Book_15_paper_0.geometry} material={materials.Book_15_paper} />
          </group>
          <group position={[0.069, -0.108, 0.686]} rotation={[Math.PI / 2, -0.179, 0]} scale={1.371}>
            <mesh geometry={nodes.Book_16_Book_16_0.geometry} material={materials.Book_16} />
            <mesh geometry={nodes.Book_16_Book_16_paper_0.geometry} material={materials.Book_16_paper} />
          </group>
          <group position={[0.085, 0.24, 0.379]} scale={1.322}>
            <mesh geometry={nodes.Book_17_Book_17_0.geometry} material={materials.Book_17} />
            <mesh geometry={nodes.Book_17_Book_17_paper_0.geometry} material={materials.Book_17_paper} />
          </group>
          <mesh geometry={nodes.Shelf_frame_Shelf_frame_0.geometry} material={materials.Shelf_frame} />
          <mesh geometry={nodes.Shelf_1_Shelf_0.geometry} material={materials.Shelf} position={[0, -0.101, 1.605]} scale={0.2} />
          <mesh geometry={nodes.Shelf_2_Shelf_0.geometry} material={materials.Shelf} position={[0, 0.099, 1.205]} scale={0.2} />
          <mesh geometry={nodes.Shelf_3_Shelf_0.geometry} material={materials.Shelf} position={[0, -0.101, 0.805]} scale={0.2} />
          <mesh geometry={nodes.Shelf_4_Shelf_0.geometry} material={materials.Shelf} position={[0, 0.099, 0.405]} scale={0.2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/Bookcase/bookcase.gltf')
