/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 chair.gltf 
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/chloe-accent-chair-honey-yellow-5a04deabddda40d48f32f71ba5653390
Title: Chloe Accent Chair, Honey Yellow
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Chair(props) {
  const { nodes, materials } = useGLTF('/3dModels/Chair/chair.gltf'); 
  return (
    <group {...props} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Chloe_Accent_Chair_FABRIC_0.geometry} material={materials.FABRIC} />
        <mesh geometry={nodes.Chloe_Accent_Chair_WOOD_0.geometry} material={materials.WOOD} />
      </group>
      <mesh geometry={nodes.Plane001_FLOOR_0.geometry} material={materials.FLOOR} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload('/3dModels/Chair/chair.gltf'); 

