/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 table.gltf 
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/simple-dining-table-a6deba91a7f9435082369e33f8db0dd6
Title: Simple dining table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/3dModels/Table/table.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 623.212, 30.011]} scale={989.925}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.qita} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lvzhi} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.zhuoyi} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.boli} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.niunai} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.boli} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.niunai} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/Table/table.gltf')
