/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 window.gltf 
Author: Mário Mendes (https://sketchfab.com/mariomendesdeveloper)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-bd087ed6ca314a9d9e39c0fa04239c14
Title: Window
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Window(props) {
  const { nodes, materials } = useGLTF('/3dModels/Window/window.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-230.309, -0.557, 6.77]} rotation={[0, -0.001, 0]} scale={2.734}>
          <mesh geometry={nodes.LeftWindow_window_0.geometry} material={materials.window} />
          <mesh geometry={nodes.LeftWindow_windowGlass_0.geometry} material={materials.windowGlass} />
        </group>
        <group position={[236.287, -0.557, 6.77]} rotation={[0, 0.001, 0]} scale={100}>
          <mesh geometry={nodes.RightWindow_window_0.geometry} material={materials.window} />
          <mesh geometry={nodes.RightWindow_windowGlass_0.geometry} material={materials.windowGlass} />
        </group>
        <mesh geometry={nodes.frame_frame_0.geometry} material={materials.frame} position={[0.906, 200.648, -3.155]} scale={[100, 100, 118.001]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/Window/window.gltf')
